In [1]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
odd_numbers = [1, 3, 5, 7]
np.array(odd_numbers)

array([1, 3, 5, 7])

In [4]:
matrix = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
np.array(matrix)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.random.rand(7)

array([0.24740675, 0.28169407, 0.71491457, 0.80356646, 0.26898639,
       0.87809399, 0.76772129])

In [15]:

np.random.rand(3, 5)

array([[0.40244168, 0.67716454, 0.25517184, 0.93320692, 0.2790552 ],
       [0.19722582, 0.4420605 , 0.15191705, 0.11113402, 0.19066117],
       [0.42511892, 0.97749895, 0.48150028, 0.30391576, 0.24350232]])

In [16]:
np.random.randn(3, 5)

array([[-0.14378382,  0.28621149, -0.63280938,  0.62539878,  1.0308056 ],
       [-0.01816618, -0.01242926, -2.3183357 ,  0.21149999,  0.28106722],
       [ 0.48083957, -0.62393069, -0.74528212,  0.62347284, -1.13503587]])

In [17]:
np.random.randint(0, 50, 20)

array([38,  6, 13,  1, 15, 22, 39, 10, 28, 12, 38,  4, 18, 24,  9, 45, 38,
       24, 12, 36])

In [18]:
np.random.randint(0, 50, (3, 4))

array([[44, 21, 11, 25],
       [ 5, 44, 11, 30],
       [ 2, 15, 46, 48]])

In [19]:
random_array = np.random.randint(0, 50, 20)

In [20]:
random_array

array([39, 45, 41, 11, 25, 36, 21,  7, 15, 47, 14, 21, 35,  4,  3, 20,  5,
       45, 11, 44])

In [21]:
new_random_array = np.arange(20)

In [23]:
new_random_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
random_array.reshape((4, 5))

array([[39, 45, 41, 11, 25],
       [36, 21,  7, 15, 47],
       [14, 21, 35,  4,  3],
       [20,  5, 45, 11, 44]])

In [25]:
new_random_array.reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [26]:
random_array.max()

47

In [27]:
random_array.argmax()

9

In [28]:
print(new_random_array.max())
print(new_random_array.argmax())

19
19


In [30]:
print(random_array.min())
print(random_array.argmin())
print()
print(new_random_array.min())
print(new_random_array.argmin())

3
14

0
0


In [31]:
reshaped_array = random_array.reshape(10, 2)

In [34]:
print(reshaped_array.shape)
print()
print(reshaped_array)

(10, 2)

[[39 45]
 [41 11]
 [25 36]
 [21  7]
 [15 47]
 [14 21]
 [35  4]
 [ 3 20]
 [ 5 45]
 [11 44]]


In [35]:
reshaped_array.dtype

dtype('int64')

In [36]:
string_array = ['cat', 'dog', 'wolf', 'rabbit', 'fox', 'duck']

In [38]:
reshaped_string = np.array(string_array).reshape(3, 2)

In [39]:
print(reshaped_string, end='\n\n')
print(reshaped_string.shape, end='\n\n')
print(reshaped_string.dtype, end='\n')

[['cat' 'dog']
 ['wolf' 'rabbit']
 ['fox' 'duck']]

(3, 2)

<U6
